<div id="copyright">
    <div class="standard_wrapper" style="text-shadow: 0pt 1px rgb(0, 0, 0);">
        <div style="float: right;">
            <p>For more information contact me at <a href="mailto:<?= $this->supportEmail = Zend_Registry::get('config')->company->email->support;
?>"> my email</a></p>
        </div>
        <div style="float: left;"> Copyright &copy; 2011 <a href="http://programmingmate.com">ProgrammingMate.com</a></div>
        
    </div>
</div>
