<br/>
<h1>INFO ABOUT THE APP</h1>
<div class="container_12">
    <div class="grid_10 prefix_1 suffic_1"><h4 class="italics">Some basic info about the application you're about to learn a lot from ;)... Hope I don't mix things up too much and I actually make sense (after all, English is not my first language, you know?).</h4></div>
    <div class="clear"></div>
    <div id="info_four">
        <div class="grid_3"><h3>Doctrine 2</h3><br/><p>This was actually the hardest part so I hope my code is clean enough. I had previously installed Doctrine 1.x in a different ZF project, and the whole thing was a little bit too messy to me (it was a modular installation so I kind of had it coming). It's not necessary to say that it wasn't a very pleasurable experience, and since ZF2 is supposed to use Doctrine 2 why wait and deal with a maintainance nightmare?</p><p><strong>Doctrine 2</strong> wasn't a walk in the park neither, but luckly I kept the pace (on being annoying to #doctrine and StackOverflow) and eventually I realized I had 3 basic concepts missing: Array Collections, Services and Repositories</p><p>After learning those three, things became much clearer and I guess, someone might feel the same about it.</p></div>
        <div class="grid_3"><h3>Zend_Acl</h3><br/><p>I guess I did a lot about this one too, and of course... it had to be <i>n'sync</i> with <strong>Doctrine 2</strong>, but that's ok... I liked the challenge and I learned a here too. </p><p>I particularly enjoyed working with Zend_Acl...and I didn't do anything too fancy, but Zend took care of it anyways, the roles system is such a time-saver</p></div>
        <div class="grid_3"><h3>Zend_Navigation</h3><br/><p>A real treat as well. I do have to admit that I regret having worked with the XML version of it, because the documentation about it isn't that great at all, so if I were to start this project from scratch I would do it completely with php (this project first started using Zend_Db, then Doctrine 1.x and now Doctrine 2...so you'll understand my "lazyness" about doing a fourth version of it) as the documentation rocks and it does allow you to a more flexible approach (thus...100 times more verbose though).</p><p>This one complemented Zend_Acl/Zend_Auth like a charm anyways, so overall...I'm pretty glad to have learned about Zend_Navigation</p></div>
        <div class="grid_3"><h3>960 Grid</h3><br/><p>In the original app I used a lot more MVC-related things, however I better don't forget talking about my most recent experiment (and the one I'm using as I type this if you actually care enough to check the phtml): <strong>the 960 grid</strong></p><p>I first learnt about the framework browsing for css solutions to standarize markup rendering on all browsers for my web design projects...I never looked back and of course...I just had to use it here too!</p></div>
        <div class="push"></div>
    </div>
    <div class="clear"></div>
    <div class="grid_10 prefix_1 suffic_1"><p class="italics">Anyways,...not the prettiest app you'll see in your life...I know. But I hope it's good enough to learn a couple of things from it. Also, I'm far from perfect... so if you see something that sucks and you know a better way of doing it...please let me know so we can both improve from this. --Federico Mendez</p></div>
    
</div>

